-- BASELINE MIGRATION — intentionally empty SQL
--
-- The Supabase database already contains the following objects (created
-- before Prisma Migrate was introduced to this project):
--
--   Enums  : content_origin, asset_status, retention_state
--   Tables : users, portfolios, assets
--
-- Running CREATE TYPE / CREATE TABLE against those existing objects would
-- fail immediately with "already exists" errors.
--
-- Strategy: this migration carries no DDL so that `prisma migrate deploy`
-- records it as applied in _prisma_migrations without touching the DB.
-- The actual new objects (job_status enum + submission_jobs table) are
-- created by the next migration:
--   20260402000001_add_submission_jobs
--
-- Full reference DDL (for documentation only — NOT executed):
--
-- CREATE TYPE "content_origin" AS ENUM ('ai','non-ai');
-- CREATE TYPE "asset_status"   AS ENUM ('draft','ready','submitted','accepted','rejected','distributed','original_deleted','thumbnail_only');
-- CREATE TYPE "retention_state" AS ENUM ('active','deleted','archived');
-- CREATE TABLE "users"      ( "id" UUID PRIMARY KEY, "email" TEXT UNIQUE NOT NULL, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ );
-- CREATE TABLE "portfolios" ( "id" UUID PRIMARY KEY, "user_id" UUID REFERENCES users ON DELETE CASCADE, "name" TEXT NOT NULL, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ );
-- CREATE TABLE "assets"     ( "id" UUID PRIMARY KEY, "portfolio_id" UUID REFERENCES portfolios ON DELETE CASCADE, ... );

